language: php

php:
  - 7.4
  - 8.0
  - 8.1

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-dist -o

script:
  - vendor/bin/phpspec run --format=dot